/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accountadd: typeof import('./src/components/account/accountadd.vue')['default']
    Accountdetail: typeof import('./src/components/account/accountdetail.vue')['default']
    AccountDetail: typeof import('./src/components/account/accountDetail.vue')['default']
    Accountedit: typeof import('./src/components/account/accountedit.vue')['default']
    AccountEdit: typeof import('./src/components/account/accountEdit.vue')['default']
    Accountform: typeof import('./src/components/account/accountform.vue')['default']
    AccountList: typeof import('./src/components/account/accountList.vue')['default']
    AccountListItem: typeof import('./src/components/account/accountListItem.vue')['default']
    AccountListItemDetail: typeof import('./src/components/account/accountListItemDetail.vue')['default']
    Accountstatis: typeof import('./src/components/accountstatis/accountstatis.vue')['default']
    Accountuserform: typeof import('./src/components/accountuser/accountuserform.vue')['default']
    copy: typeof import('./src/components/account/accountListItem copy.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Mainnavbar: typeof import('./src/components/mainnavbar/mainnavbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./src/components/user/user.vue')['default']
    UserList: typeof import('./src/components/accountuser/userList.vue')['default']
    UserListItem: typeof import('./src/components/accountuser/userListItem.vue')['default']
  }
}
