/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accountform: typeof import('./src/components/account/accountform.vue')['default']
    AccountList: typeof import('./src/components/account/accountList.vue')['default']
    AccountListItem: typeof import('./src/components/account/accountListItem.vue')['default']
    Accountuserform: typeof import('./src/components/accountuser/accountuserform.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./src/components/user/user.vue')['default']
    UserList: typeof import('./src/components/accountuser/userList.vue')['default']
    UserListItem: typeof import('./src/components/accountuser/userListItem.vue')['default']
  }
}
