/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accountdetail: typeof import('./src/components/account/accountdetail.vue')['default']
    Accountedit: typeof import('./src/components/account/accountedit.vue')['default']
    Accountform: typeof import('./src/components/account/accountform.vue')['default']
    AccountList: typeof import('./src/components/account/accountList.vue')['default']
    AccountListItem: typeof import('./src/components/account/accountListItem.vue')['default']
    Accountstatis: typeof import('./src/components/accountstatis/accountstatis.vue')['default']
    AccountunpayList: typeof import('./src/components/account/accountunpayList.vue')['default']
    Accountuser: typeof import('./src/components/accountuser/accountuser.vue')['default']
    Accountuserdetail: typeof import('./src/components/accountuser/accountuserdetail.vue')['default']
    Accountuseredit: typeof import('./src/components/accountuser/accountuseredit.vue')['default']
    Accountuserform: typeof import('./src/components/accountuser/accountuserform.vue')['default']
    Accountusermain: typeof import('./src/components/accountuser/accountusermain.vue')['default']
    Booktype: typeof import('./src/components/common/booktype.vue')['default']
    Booktype2: typeof import('./src/components/common/booktype2.vue')['default']
    copy: typeof import('./src/components/common/booktype copy.vue')['default']
    ElTree: typeof import('element-plus/es')['ElTree']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Login: typeof import('./src/components/common/login.vue')['default']
    Mainnavbar: typeof import('./src/components/mainnavbar/mainnavbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Topover: typeof import('./src/components/common/topover.vue')['default']
    User: typeof import('./src/components/user/user.vue')['default']
    Useredit: typeof import('./src/components/user/useredit.vue')['default']
    UserList: typeof import('./src/components/accountuser/userList.vue')['default']
    UserListItem: typeof import('./src/components/accountuser/userListItem.vue')['default']
  }
}
